### ISSUE TITLE
Problem Solving

### ISSUE THREAD

**Issue by abhyudaya12** [UbaydullohML/hacckerrank#3]
What can I do to improve my problem-solving skills???

**Comment by UbaydullohML** [comment]
Hi, I would recommend to practice below link questions:
https://www.hackerrank.com/domains/algorithms

**Comment by UbaydullohML** [comment]
This issue has been resolved

**Comment by UbaydullohML** [comment]
done

**Comment by abhyudaya12** [comment]
Thanks dude!!!
